apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment

spec:

  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      labels:
        app: backend

    spec:

      containers:

      - name: backend

        #image: flask-backend
        image: us-central1-docker.pkg.dev/project-174cc443-c77e-47fb-ac5/repo-virtualizacion/backend:1.0

        #imagePullPolicy: Never

        ports:
        - containerPort: 5000

        env:

        - name: MONGO_HOST
          value: mongo-service

        - name: MONGO_PORT
          value: "27017"

        - name: MONGO_DB
          value: "login_db"