apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment

spec:

  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:

    metadata:
      labels:
        app: frontend

    spec:

      containers:

      - name: frontend

        #image: vue-frontend
        image: us-central1-docker.pkg.dev/project-174cc443-c77e-47fb-ac5/repo-virtualizacion/frontend:2.0

        #imagePullPolicy: Never

        ports:
        - containerPort: 5508